// Define main function (script entry)
// ä½œä¸ºä¸€ä¸ªå°ç™½ï¼Œä¸ºäº†æ–¹ä¾¿å°ç™½å†™verge-revè„šæœ¬ï¼Œåœ¨æ­¤æä¾›ä¸€ä¸ªå…¨å±€Scriptè„šæœ¬æ¨¡æ¿ï¼Œæ–¹ä¾¿å°ç™½Ctrl+C&V
// ä½¿ç”¨ï¼šå¤åˆ¶å…¨éƒ¨å†…å®¹åˆ°verge-revçš„å…¨å±€æ‰©å±•è„šæœ¬ä¸­ï¼Œç„¶åè·Ÿæ®éœ€è¦ä¿®æ”¹
// æ­¤è„šæœ¬æ¨¡æ¿é€‚ç”¨äºverge-revçš„1.7.3ä»¥ä¸Šç‰ˆæœ¬ï¼Œé€‚ç”¨äºå¤šéœ€æ±‚ã€å¤šè®¾å¤‡ã€å¤šäººåˆ‡æ¢ä½¿ç”¨
// åŒ…å«åŠŸèƒ½ï¼šé’ˆå¯¹ä½¿ç”¨éœ€æ±‚ç­›é€‰è®¢é˜…ï¼Œè¿›è¡Œåˆ†ç»„ã€è§„åˆ™ç­‰å­—æ®µå†…å®¹çš„è¦†ç›–ä»¥åŠå¯¹å…¶rulesã€proxiesã€rule-providersè¿›è¡Œprepend/append
// ä»¥ä¸‹çš„addConfigå‡½æ•°ã€prependå‡½æ•°ã€appendå‡½æ•°ï¼Œå°ç™½è¯·å‹¿ä¿®æ”¹ï¼Œå¦åˆ™ä¼šå¯¼è‡´è„šæœ¬æ— æ³•æ­£å¸¸è¿è¡Œï¼Œå¤§ä½¬è¯·è‡ªä¾¿
const addConfig = (name, usage, config, filename) => {
    if (name.test(filename)) {
        for (let key in Sub[usage]) config[key] = Sub[usage][key];
        for (let i in Extra[usage].preExtra) prepend(config, ...Extra[usage].preExtra[i]);
        for (let j in Extra[usage].appExtra) append(config, ...Extra[usage].appExtra[j]);
    }
}

const prepend = (config, type, content) => {
    if (Array.isArray(content) && content.length > 0) {
        if (type == 'proxies') config.proxies.unshift(...content);
        if (type == 'proxy-groups') config['proxy-groups'].unshift(...content);
        if (type == 'rules') config.rules.unshift(...content);
    }
}

const append = (config, type, content) => {
    if (Array.isArray(content) && content.length > 0) {
        if (type == 'proxies') config.proxies.push(...content);
        if (type == 'proxy-groups') config['proxy-groups'].push(...content);
        if (type == 'rules') config.rules.push(...content);
    }
}

// å›½å†…DNSæœåŠ¡å™¨
const domesticNameservers = [
    "https://dns.alidns.com/dns-query", // é˜¿é‡Œäº‘å…¬å…±DNS
    "https://doh.pub/dns-query", // è…¾è®¯DNSPod
    "https://doh.360.cn/dns-query" // 360å®‰å…¨DNS
];
// å›½å¤–DNSæœåŠ¡å™¨
const foreignNameservers = [
    "https://1.1.1.1/dns-query", // Cloudflare(ä¸»)
    "https://1.0.0.1/dns-query", // Cloudflare(å¤‡)
    "https://208.67.222.222/dns-query", // OpenDNS(ä¸»)
    "https://208.67.220.220/dns-query", // OpenDNS(å¤‡)
    "https://194.242.2.2/dns-query", // Mullvad(ä¸»)
    "https://194.242.2.3/dns-query" // Mullvad(å¤‡)
];
// Subéƒ¨åˆ†æ˜¯å®ç°å¯¹dns, proxy-groups, rulesç­‰è®¢é˜…é…ç½®æ–‡ä»¶ä¸­æ‰€è§„å®šå­—æ®µçš„å†…å®¹è¿›è¡Œè¦†ç›–ï¼Œå…¶ä»–è§„å®šå­—æ®µä¹Ÿé€‚ç”¨
const Sub = {
    // åœ¨æ­¤å¤„å¡«å…¥'ä½¿ç”¨éœ€æ±‚': {}ï¼Œç”¨äºåŒ¹é…ç›¸åº”çš„é…ç½®
    // æ³¨æ„ï¼šåˆ«ä¸¢å¼•å·ï¼é˜²æ­¢å‡ºé”™ï¼å¤šä¸ªé…ç½®ä¹‹é—´ç”¨<è‹±æ–‡çš„é€—å·>éš”å¼€
    'å®¶ç”¨': {},
    // ä»¥ä¸‹é…ç½®ä¸ºä¸€ä¸ªç¤ºä¾‹ï¼Œå¯ä»¥è‡ªè¡Œå‚è€ƒ
    'å…¬å¸ç”¨': {// æ­¤å¤„æ­£åˆ™è¡¨è¾¾å¼æ„ä¸ºï¼šåŒ¹é…æ‰€æœ‰åä¸ä¸ºmeta.yamlçš„æ–‡ä»¶ï¼Œæœ‰éœ€è¦å¯ä»¥è‡ªè¡Œå­¦ä¹ 
        // ä»¥ä¸‹æ˜¯éœ€è¦è¦†ç›–çš„dnsé…ç½®ï¼Œæœ‰éœ€æ±‚çš„è¯å¯ä»¥è‡ªè¡Œå‚è€ƒå®˜æ–¹æ–‡æ¡£ä¿®æ”¹ï¼Œä¸éœ€è¦çš„æŠŠè¿™ä¸€é¡¹å…¨éƒ¨åˆ é™¤å³å¯
        'dns': {
            // è¿™é‡Œç•™ç©ºä¼šæ¸…ç©ºdnsé…ç½®ï¼Œä»¥ä¸‹å†…å®¹ä¸ºç¤ºä¾‹
            "enable": true,
            "listen": "0.0.0.0:1053",
            "ipv6": true,
            "use-system-hosts": false,
            "cache-algorithm": "arc",
            "enhanced-mode": "fake-ip",
            "fake-ip-range": "198.18.0.1/16",
            "fake-ip-filter": [
                // æœ¬åœ°ä¸»æœº/è®¾å¤‡
                "+.lan",
                "+.local",
                // Windowsç½‘ç»œå‡ºç°å°åœ°çƒå›¾æ ‡
                "+.msftconnecttest.com",
                "+.msftncsi.com",
                // QQå¿«é€Ÿç™»å½•æ£€æµ‹å¤±è´¥
                "localhost.ptlogin2.qq.com",
                "localhost.sec.qq.com",
                // å¾®ä¿¡å¿«é€Ÿç™»å½•æ£€æµ‹å¤±è´¥
                "localhost.work.weixin.qq.com"
            ],
            "default-nameserver": ["223.5.5.5", "119.29.29.29", "1.1.1.1", "8.8.8.8"],
            "nameserver": [...domesticNameservers, ...foreignNameservers],
            "proxy-server-nameserver": [...domesticNameservers, ...foreignNameservers],
            "nameserver-policy": {
                "geosite:private,cn,geolocation-cn": domesticNameservers,
                "geosite:google,youtube,telegram,gfw,geolocation-!cn": foreignNameservers
            }
        },
        // ä»¥ä¸‹æ˜¯éœ€è¦è¦†ç›–çš„åˆ†ç»„é…ç½®ï¼Œæœ‰éœ€æ±‚çš„å¯ä»¥è‡ªè¡Œå‚è€ƒå®˜æ–¹æ–‡æ¡£ä¿®æ”¹ï¼Œä¸éœ€è¦çš„æŠŠè¿™ä¸€é¡¹å…¨éƒ¨åˆ é™¤å³å¯
        'proxy-groups': [
            {
                "name": "ğŸš€ èŠ‚ç‚¹é€‰æ‹©",
                "type": "select",
                "include-all-proxies": true,
                "proxies": [
                    "â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
                    "DIRECT"
                ]
            },
            {
                "name": "â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
                "type": "url-test",
                "url": "http://www.gstatic.com/generate_204",
                "interval": 300,
                "tolerance": 50,
                "include-all-proxies": true,
                "proxies": []
            },
            {
                "name": "ğŸŒ å›½å¤–åª’ä½“",
                "type": "select",
                "proxies": [
                    "ğŸš€ èŠ‚ç‚¹é€‰æ‹©",
                    "â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
                    "ğŸ¯ å…¨çƒç›´è¿"
                ]
            },
            {
                "name": "ğŸ“² ç”µæŠ¥ä¿¡æ¯",
                "type": "select",
                "proxies": [
                    "ğŸš€ èŠ‚ç‚¹é€‰æ‹©",
                    "ğŸ¯ å…¨çƒç›´è¿"
                ]
            },
            {
                "name": "â“‚ï¸ å¾®è½¯æœåŠ¡",
                "type": "select",
                "proxies": [
                    "ğŸ¯ å…¨çƒç›´è¿",
                    "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
                ]
            },
            {
                "name": "ğŸ è‹¹æœæœåŠ¡",
                "type": "select",
                "proxies": [
                    "ğŸ¯ å…¨çƒç›´è¿",
                    "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
                ]
            },
            {
                "name": "ğŸ“¢ è°·æ­ŒFCM",
                "type": "select",
                "proxies": [
                    "ğŸš€ èŠ‚ç‚¹é€‰æ‹©",
                    "ğŸ¯ å…¨çƒç›´è¿",
                    "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
                ]
            },
            {
                "name": "ğŸ¯ å…¨çƒç›´è¿",
                "type": "select",
                "proxies": [
                    "DIRECT",
                    "ğŸš€ èŠ‚ç‚¹é€‰æ‹©",
                    "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
                ]
            },
            {
                "name": "ğŸ›‘ å…¨çƒæ‹¦æˆª",
                "type": "select",
                "proxies": [
                    "REJECT",
                    "DIRECT"
                ]
            },
            {
                "name": "ğŸƒ åº”ç”¨å‡€åŒ–",
                "type": "select",
                "proxies": [
                    "REJECT",
                    "DIRECT"
                ]
            },
            {
                "name": "ğŸŸ æ¼ç½‘ä¹‹é±¼",
                "type": "select",
                "proxies": [
                    "ğŸš€ èŠ‚ç‚¹é€‰æ‹©",
                    "ğŸ¯ å…¨çƒç›´è¿",
                    "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
                ]
            }
        ],
        // ä»¥ä¸‹æ˜¯éœ€è¦è¦†ç›–çš„è§„åˆ™é…ç½®ï¼Œæœ‰éœ€æ±‚çš„å¯ä»¥è‡ªè¡Œå‚è€ƒå®˜æ–¹æ–‡æ¡£ä¿®æ”¹ï¼Œä¸éœ€è¦çš„æŠŠè¿™ä¸€é¡¹å…¨éƒ¨åˆ é™¤å³å¯
        // æ³¨æ„è§„åˆ™ã€åˆ†ç»„ã€è§„åˆ™é›†çš„å¯¹åº”
        'rules': [
            "RULE-SET,PersonalDirect,ğŸ¯ å…¨çƒç›´è¿",
            "RULE-SET,PersonalProxy,ğŸš€ èŠ‚ç‚¹é€‰æ‹©",
            "RULE-SET,LocalAreaNetwork,ğŸ¯ å…¨çƒç›´è¿",
            "RULE-SET,UnBan,ğŸ¯ å…¨çƒç›´è¿",
            "RULE-SET,GoogleCN,ğŸ¯ å…¨çƒç›´è¿",
            "RULE-SET,SteamCN,ğŸ¯ å…¨çƒç›´è¿",
            "RULE-SET,ChinaDomain,ğŸ¯ å…¨çƒç›´è¿",
            "RULE-SET,ChinaCompanyIp,ğŸ¯ å…¨çƒç›´è¿",
            "RULE-SET,BanAD,ğŸ›‘ å…¨çƒæ‹¦æˆª",
            "RULE-SET,BanProgramAD,ğŸƒ åº”ç”¨å‡€åŒ–",
            "RULE-SET,GoogleFCM,ğŸ“¢ è°·æ­ŒFCM",
            "RULE-SET,Microsoft,â“‚ï¸ å¾®è½¯æœåŠ¡",
            "RULE-SET,Apple,ğŸ è‹¹æœæœåŠ¡",
            "RULE-SET,Telegram,ğŸ“² ç”µæŠ¥ä¿¡æ¯",
            "RULE-SET,ProxyMedia,ğŸŒ å›½å¤–åª’ä½“",
            "RULE-SET,ProxyLite,ğŸš€ èŠ‚ç‚¹é€‰æ‹©",
            "GEOIP,CN,ğŸ¯ å…¨çƒç›´è¿",
            "MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼"
        ],
        // ä»¥ä¸‹æ˜¯éœ€è¦è¦†ç›–çš„è§„åˆ™é›†é…ç½®ï¼Œæœ‰éœ€æ±‚çš„å¯ä»¥è‡ªè¡Œå‚è€ƒå®˜æ–¹æ–‡æ¡£ä¿®æ”¹ï¼Œä¸éœ€è¦çš„æŠŠè¿™ä¸€é¡¹å…¨éƒ¨åˆ é™¤å³å¯
        'rule-providers': {
            "LocalAreaNetwork": {
                "type": "http",
                "behavior": "classical",
                "url": "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/LocalAreaNetwork.yaml",
                "interval": 86400,
                "path": "./profiles/ACL4SSR/LocalAreaNetwork.yaml"
            },
            "UnBan": {
                "type": "http",
                "behavior": "classical",
                "url": "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/UnBan.yaml",
                "interval": 86400,
                "path": "./profiles/ACL4SSR/UnBan.yaml"
            },
            "GoogleCN": {
                "type": "http",
                "behavior": "classical",
                "url": "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleCN.yaml",
                "interval": 86400,
                "path": "./profiles/ACL4SSR/GoogleCN.yaml"
            },
            "SteamCN": {
                "type": "http",
                "behavior": "classical",
                "url": "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/SteamCN.yaml",
                "interval": 86400,
                "path": "./profiles/ACL4SSR/SteamCN.yaml"
            },
            "ChinaDomain": {
                "type": "http",
                "behavior": "classical",
                "url": "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaDomain.yaml",
                "interval": 86400,
                "path": "./profiles/ACL4SSR/ChinaDomain.yaml"
            },
            "ChinaCompanyIp": {
                "type": "http",
                "behavior": "ipcidr",
                "url": "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaCompanyIp.yaml",
                "interval": 86400,
                "path": "./profiles/ACL4SSR/ChinaCompanyIp.yaml"
            },
            "BanAD": {
                "type": "http",
                "behavior": "classical",
                "url": "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml",
                "interval": 86400,
                "path": "./profiles/ACL4SSR/BanAD.yaml"
            },
            "BanProgramAD": {
                "type": "http",
                "behavior": "classical",
                "url": "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanProgramAD.yaml",
                "interval": 86400,
                "path": "./profiles/ACL4SSR/BanProgramAD.yaml"
            },
            "GoogleFCM": {
                "type": "http",
                "behavior": "classical",
                "url": "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleFCM.yaml",
                "interval": 86400,
                "path": "./profiles/ACL4SSR/GoogleFCM.yaml"
            },
            "Microsoft": {
                "type": "http",
                "behavior": "classical",
                "url": "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Microsoft.yaml",
                "interval": 86400,
                "path": "./profiles/ACL4SSR/Microsoft.yaml"
            },
            "Apple": {
                "type": "http",
                "behavior": "classical",
                "url": "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Apple.yaml",
                "interval": 86400,
                "path": "./profiles/ACL4SSR/Apple.yaml"
            },
            "Telegram": {
                "type": "http",
                "behavior": "classical",
                "url": "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Telegram.yaml",
                "interval": 86400,
                "path": "./profiles/ACL4SSR/Telegram.yaml"
            },
            "ProxyMedia": {
                "type": "http",
                "behavior": "classical",
                "url": "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyMedia.yaml",
                "interval": 86400,
                "path": "./profiles/ACL4SSR/ProxyMedia.yaml"
            },
            "ProxyLite": {
                "type": "http",
                "behavior": "classical",
                "url": "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyLite.yaml",
                "interval": 86400,
                "path": "./profiles/ACL4SSR/ProxyLite.yaml"
            }
        }
    }
};

// Extraéƒ¨åˆ†æ˜¯å¯¹rulesã€proxiesã€rule-providersè§„å®šå­—æ®µå®ç°prepend/appendåŠŸèƒ½ï¼Œä¸é€‚ç”¨å…¶ä»–è§„å®šå­—æ®µ
const Extra = {
    'å®¶ç”¨': {},
    'å…¬å¸ç”¨': {
        preExtra: [
            ['rules',
                [
                    // æ­¤å¤„å¡«å†™æ·»åŠ çš„è§„åˆ™ï¼Œç›´æ¥å†™å­—ç¬¦ä¸²ï¼Œå¤šä¸ªè§„åˆ™ç”¨è‹±æ–‡é€—å·éš”å¼€ï¼Œä¸éœ€è¦å¯ä»¥ç•™ç©º
                    // "RULE-SET,ProxyLite,ğŸš€ èŠ‚ç‚¹é€‰æ‹©",
                    // "GEOIP,CN,ğŸ¯ å…¨çƒç›´è¿", "MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼",
                ]
            ],
            ['proxies',
                [
                    // æ­¤å¤„å¡«å†™æ·»åŠ çš„èŠ‚ç‚¹ï¼Œæ³¨æ„æ˜¯æ¯ä¸ªèŠ‚ç‚¹éƒ½æ˜¯{...}æ ¼å¼ï¼Œä¸æ˜¯[]æ ¼å¼ï¼Œå¤šä¸ªèŠ‚ç‚¹ç”¨è‹±æ–‡é€—å·éš”å¼€ï¼Œä¸éœ€è¦å¯ä»¥ç•™ç©º
                    // {
                    //     "name": "çœŸçš„æ˜¯ä½ å‘€",
                    //     "type": "trojan",
                    //     "server": "0.0.0.0",
                    //     "port": 443,
                    //     "password": "00000000000",
                    //     "network": "ws",
                    //     "udp": true,
                    //     "sni": "0.0.0.0",
                    //     "skip-cert-verify": true
                    // },
                ]
            ],
            ['rule-providers',
                {
                    // æ­¤å¤„å¡«å†™æ·»åŠ çš„è§„åˆ™é›†ï¼Œæ³¨æ„æ˜¯æ¯ä¸ªè§„åˆ™é›†æ ¼å¼ï¼šåå­—:{...}ï¼Œå¤šä¸ªè§„åˆ™é›†ç”¨è‹±æ–‡é€—å·éš”å¼€ï¼Œä¸éœ€è¦å¯ä»¥ç•™ç©º
                    // "LocalAreaNetwork": {
                    //     "type": "http",
                    //     "behavior": "classical",
                    //     "interval": 86400,
                    //     "url": "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/LocalAreaNetwork.yaml",
                    //     "path": "./profiles/ACL4SSR/LocalAreaNetwork.yaml"
                    // },
                    // "UnBan": {
                    //     "type": "http",
                    //     "behavior": "classical",
                    //     "interval": 86400,
                    //     "url": "https://raw.gitmirror.com/ACL4SSR/ACL4SSR/master/Clash/Providers/UnBan.yaml",
                    //     "path": "./profiles/ACL4SSR/UnBan.yaml"
                    // }
                }
            ]
        ],
        // æ­¤å¤„å†…å®¹ä¸ä¸Šé¢ç›¸åŒï¼Œä¸åšå¤šä½™è¡¨è¿°
        appExtra: [
            ['rules',
                [
                    // æ­¤å¤„å¡«å†™æ·»åŠ çš„è§„åˆ™ï¼Œç›´æ¥å†™å­—ç¬¦ä¸²ï¼Œå¤šä¸ªè§„åˆ™ç”¨è‹±æ–‡é€—å·éš”å¼€ï¼Œä¸éœ€è¦å¯ä»¥ç•™ç©º
                ]
            ],
            ['proxies',
                [
                    // æ­¤å¤„å¡«å†™æ·»åŠ çš„èŠ‚ç‚¹ï¼Œæ³¨æ„æ˜¯æ¯ä¸ªèŠ‚ç‚¹éƒ½æ˜¯{...}æ ¼å¼ï¼Œä¸æ˜¯[]æ ¼å¼ï¼Œå¤šä¸ªèŠ‚ç‚¹ç”¨è‹±æ–‡é€—å·éš”å¼€ï¼Œä¸éœ€è¦å¯ä»¥ç•™ç©º
                ]
            ],
            ['rule-providers',
                {
                    // æ­¤å¤„å¡«å†™æ·»åŠ çš„è§„åˆ™é›†ï¼Œæ³¨æ„æ˜¯æ¯ä¸ªè§„åˆ™é›†æ ¼å¼ï¼šåå­—:{...}ï¼Œå¤šä¸ªè§„åˆ™é›†ç”¨è‹±æ–‡é€—å·éš”å¼€ï¼Œä¸éœ€è¦å¯ä»¥ç•™ç©º
                }
            ]
        ]
    }
};

function main(config, filename) {
    // åœ¨ä¸Šé¢é…ç½®å®Œæ¯•ï¼Œå°±å¯ä»¥åœ¨æ­¤å¤„è°ƒç”¨addConfigå‡½æ•°æ·»åŠ èŠ‚ç‚¹ã€è§„åˆ™ã€è§„åˆ™é›†ç­‰
    // æ ¼å¼ä¸º addConfig(æ­£åˆ™è¡¨è¾¾å¼, ä½¿ç”¨éœ€æ±‚, config, filename);
    // åªéœ€è¦ä¿®æ”¹æ­£åˆ™è¡¨è¾¾å¼å’Œä½¿ç”¨éœ€æ±‚çš„å†…å®¹ï¼Œconfigå’Œfilenameä¸éœ€è¦ä¿®æ”¹
    // æ³¨æ„æ­£åˆ™è¡¨è¾¾å¼çš„2ä¸ªæ–œæ ä¸èƒ½ä¸¢ï¼Œå…·ä½“ä½¿ç”¨æ–¹æ³•å¯ä»¥è‡ªè¡Œå­¦ä¹ 
    addConfig(/^.*$/, 'å®¶ç”¨', config, filename); // /^.*$/è¡¨ç¤ºç­›é€‰æ‰€æœ‰è®¢é˜…ï¼Œ'å®¶ç”¨'è¡¨ç¤ºä½¿ç”¨éœ€æ±‚å¯¹åº”ä¸Šæ–‡çš„é…ç½®ï¼Œconfigå’Œfilenameä¿æŒåŸæ ·

    // å¦‚æœæœ‰å¤šä¸ªä½¿ç”¨éœ€æ±‚ï¼Œå¯ä»¥ç»§ç»­æ·»åŠ 
    return config;
}
